#!/bin/bash
set -e

# Make sure classic notebook is installed
pip install notebook pandas

# Ensure Jupyter sees the Lucra theme
mkdir -p ~/.jupyter/custom
cp .jupyter/custom/custom.css ~/.jupyter/custom/custom.css